<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ai_robot</name>
  <version>0.1.0</version>
  <description>AI Robot Demo V3: DeepSeek brain + memory connected to ROS2</description>
  <maintainer email="zlx06@example.com">zlx06</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>python3-dotenv</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
